[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% if version %}## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | split(pat=": ") | last | trim }}{% if commit.breaking %} [breaking]{% endif %}
{% endfor %}
{% endfor %}

"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = true
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Fixes" },
    { message = "^refactor", group = "Refactors" },
    { message = "^perf", group = "Performance" },
    { message = "^test", group = "Testing" },
    { message = "^docs?", group = "Documentation" },
    { message = "^build", group = "Build" },
    { message = "^ci", group = "CI" },
    { message = "^chore", group = "Chores" },
    { message = "^release", skip = true },
    { message = "^Merge", skip = true },
]
link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/mfmezger/ragcli/issues/$1" },
]
